openvpn: add bash to RDEPENDS
OpenVPN fails with:
    ERROR: openvpn-2.4.7-r0 do_package_qa: QA Issue:
    /etc/openvpn-misc/upscript.sh contained in package openvpn requires
    /bin/bash, but no providers found in RDEPENDS_openvpn? [file-rdeps]

Add bash to RDEPENDS to fix qa error.

Change-type: patch
Signed-off-by: Joseph Kogut <joseph.kogut@gmail.com>