kernel-resin.bbclass: Fix getVar() invocation
Since poky c7610aa353e31977c099ce574acb188a3f4219e0 , default expand=False has been dropped.
Hence, we need to explictily set the expand parameter in order to fix the following error:

     0322:# Inject resin configs
     0323:#
     0324:python do_kernel_resin_injectconfig() {
 *** 0325:    activatedflags = d.getVar("RESIN_CONFIGS").split()
     0326:    if not activatedflags:
     0327:        bb.warn("No resin specific kernel configuration flags selected.")
     0328:        return
     0329:
Exception: TypeError: getVar() missing 1 required positional argument: 'expand'

Signed-off-by: Florin Sarbu <florin@resin.io>