kernel-modules-headers.bbappend: Fix missing openssl/bio.h
Adding the dependency on openssl fixes the following error
when compiling a 4.16 kernel:

|   HOSTCC  scripts/extract-cert
| scripts/extract-cert.c:21:10: fatal error: openssl/bio.h:
No such file or directory

Change-type: patch
Changelog-entry: Fix kernel-modules-headers compile missing bio.h
Signed-off-by: Florin Sarbu <florin@resin.io>