balena-bootloader.bbclass: Size reduction
Newer meta-balena updates are failing for iot-gate-imx8plus-sb with the error:
ERROR: balena-image-flasher-1.0-r0 do_resin_boot_dirgen_and_deploy: resin-boot: Not enough space for atomic copy operations.

In order to have the size reduction available for all balena-bootloader users we do these changes
directly here in the balena-bootloader class.

Changelog-entry: Reduce the size of the balena bootloader by removing unused functionality
Change-type: patch
Signed-off-by: Florin Sarbu <florin@balena.io>