packagegroup-resin: Move libnss-ato out of packagegroup to avoid build error
Yocto kirkstone complains with:

ERROR: packagegroup-resin-1.0-r1 do_package_write_ipk: An allarch packagegroup shouldn't depend on packages which are dynamically renamed (libnss-ato to libnss-ato2)

For lack of a better place, move to the balena-image recipe.

Change-type: patch
Signed-off-by: Alex Gonzalez <alexg@balena.io>