kernel-balena.bbclass: Change aufs download and unpack from git fetcher to generic fetcher
With Poky commit https://git.yoctoproject.org/poky/commit/?id=ef3e46afd910d4b7727d42c4c18b501525c65695
our current unpack implementation of the aufs patches failed with:
Exception: AttributeError: 'FetchData' object has no attribute 'unpack_tracer'

To fix this we change to downloading and unpacking with the generic fetcher.

Also fix aufs compilation with kernel 6.6.65

Changelog-entry: Change kernel aufs code to be downloaded and unpacked with the generic fetcher instead of git fetcher
Signed-off-by: Florin Sarbu <florin@balena.io>