initramfs-framework: Morty already has the PACKAGE initramfs-module-rootfs
If we have dulicates in PACKAGES, yocto will fails with:
ERROR: initramfs-framework-1.0-r2 do_package: QA Issue: initramfs-module-rootfs
is listed in PACKAGES multiple times, this leads to packaging errors.

We fix this by only adding the initramfs-module-rootfs package in the versions
where this doesn't exist.

Signed-off-by: Andrei Gherzan <andrei@resin.io>