kernel-resin.bbclass: Fix getVar() invocation
Since poky c7610aa353e31977c099ce574acb188a3f4219e0 , default expand=False has been dropped.
Hence, we need to explictily set the expand parameter in order to fix the following error:

Exception: TypeError: getVar() takes at least 3 arguments (2 given)

Signed-off-by: Florin Sarbu <florin@resin.io>